apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      tracesToLogsV2:
        customQuery: true
        datasourceUid: "loki"
        filterBySpanID: false
        filterByTraceID: false
        query: '{service_name="$${__span.tags["service.name"]}"} | trace_id="$${__span.traceId}" | span_id="$${__span.spanId}"'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      derivedFields:
        - name: trace_id
          matcherType: label
          matcherRegex: trace_id
          url: $${__value.raw}
          datasourceUid: tempo
        - name: traceid
          matcherRegex: (?:traceid=(\w+)|\"TraceId\":\"(\w+)\")
          url: $${__value.raw}
          datasourceUid: tempo
