
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins: [ "*" ]
          allowed_headers: [ "*" ]
  prometheus/collector:
    config:
      scrape_configs:
        - job_name: 'opentelemetry-collector'
          static_configs:
            - targets: ['localhost:8888']

processors:
  attributes/cluster:
    actions:
      - key: cluster
        value: "docker-compose"
        action: upsert

exporters:
  otlphttp/metrics:
    endpoint: http://prometheus:9090/api/v1/otlp
  otlphttp/traces:
    endpoint: http://tempo:4318
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
  logging/metrics:
    verbosity: detailed
  logging/traces:
    verbosity: detailed
  logging/logs:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - attributes/cluster
      exporters: [otlphttp/traces]
    metrics:
      receivers: [otlp,prometheus/collector]
      processors: []
      exporters: [otlphttp/metrics]
    logs:
      receivers: [otlp]
      processors:
        - attributes/cluster
      exporters: [otlphttp/logs]
