server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: job
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/__meta_docker_container_id__/__meta_docker_container_id__-json.log
    pipeline_stages:
      - match:
          selector: '{job="/otel-drupal-demo-tempo-1"} |= " msg=received "'
          stages:
            - labeldrop:
                - service_name
                - job
                - level
            - logfmt:
                mapping:
                  service_name: 'span_service_name'
                  name: 'span_name'
                  span_id: 'spanid'
                  trace_id: 'traceid'
                  span_kind:
                  span_status:
                  span_duration_seconds:
            - labels:
                span_service_name: 'service_name'
                span_name: 'name'
            - structured_metadata:
                kind: 'span_kind'
                status: 'span_status'
                duration_seconds: 'span_duration_seconds'
                trace_id:
                span_id:
            - replace:
                expression: '((span_service_name|span_name|spanid|traceid|level|caller|ts|msg)="[^"]+"+\s?|(span_service_name|span_name|spanid|traceid|level|caller|ts|msg)=[^\s]+\s?)'
                replacement: ''
            - replace:
                expression: '(\bspan_)[a-zA-Z0-9_]+="[^"]|(\bspan_)[a-zA-Z0-9_]+=[^\s]+'
                replacement: ''
