{
 "title": "OpenTelemetry Apps RED",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service=~\"$service\", span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"[2-3]..\"}[$__rate_interval]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Error percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service=~\"$service\", span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"5..\"}[$__rate_interval])) / sum(rate(traces_spanmetrics_latency_count{service=~\"$service\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval]))",
     "legendFormat": "5xx Errors"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service=~\"$service\", span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"4..\"}[$__rate_interval])) / sum(rate(traces_spanmetrics_latency_count{service=~\"$service\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval]))",
     "legendFormat": "4xx Errors"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=~\"$service\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service=~\"$service\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service=~\"$service\", span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Error logs rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate({service_name=~\"$service\"} | level=\"error\" [$__auto]))",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}