{
 "title": "OpenTelemetry App",
 "tags": [ "OpenTelemetry" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count, cluster)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count,service)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{service=\"$service\"},service_version)"
    }
   },
   { "name": "quantiles", "query": "0.999,0.99,0.95,0.90,0.50" },
   { "name": "httpErrorPattern", "query": "[4-5]..|0,4..,5..,0" }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Error percentage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", cluster=~\"$cluster\", service_version=~\"$version\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) / sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) > 0",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (le)) > 0",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"$service\"} | level=\"error\" [$__auto]))",
     "legendFormat": "Error logs"
    }
   ]
  },
  {
   "title": "Http rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", cluster=~\"$cluster\", service_version=~\"$version\", http_response_status_code=~\"[2-3]..\"}[$__rate_interval])) by (span_name, http_response_status_code,)",
       "legendFormat": "{{span_name}} - {{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "Error percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"$httpErrorPattern\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (span_name, http_response_status_code) / ignoring(http_response_status_code) group_left sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (span_name)",
       "legendFormat": "{{span_name}} - {{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "HttpClient - Request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", service_version=~\"$version\", http_response_status_code=~\"[2-3]..\"}[$__rate_interval])) by (span_name, http_response_status_code)",
       "legendFormat": "{{span_name}} - {{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "HttpClient - Error percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", http_response_status_code=~\"$httpErrorPattern\", service_version=~\"$version\"}[$__rate_interval])) by (span_name, http_response_status_code) / ignoring(http_response_status_code) group_left sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", service_version=~\"$version\"}[$__rate_interval])) by (span_name)",
       "legendFormat": "{{span_name}} - {{http_response_status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Http latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"[2-3]..\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (span_name, http_response_status_code, le))",
       "legendFormat": "{{span_name}} - {{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "Http error latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"$httpErrorPattern\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (span_name, http_response_status_code, le))",
       "legendFormat": "{{span_name}} - {{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "HttpClient latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", http_response_status_code=~\"[2-3]..\", span_name!~\"HTTP .*\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (span_name, http_status_code, http_method, le))",
       "legendFormat": "{{span_name}}{{http_host}} - {{http_method}} {{http_status_code}}"
      }
     ]
    },
    {
     "title": "HttpClient error latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", http_response_status_code=~\"$httpErrorPattern\", http_host!=\"\", cluster=~\"$cluster\", span_name!~\"HTTP .*\", service_version=~\"$version\"}[$__rate_interval])) by (span_name, http_status_code, http_method, le))",
       "legendFormat": "{{span_name}}{{http_host}} - {{http_method}} {{http_status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Db rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", db_system!=\"\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (db_system, span_name)",
       "legendFormat": "{{db_system}} {{span_name}}"
      }
     ]
    },
    {
     "title": "Error percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", db_system!=\"\", status_code=\"STATUS_CODE_ERROR\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (db_system, span_name) /\nsum(rate(traces_spanmetrics_latency_count{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", db_system!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (db_system, span_name)",
       "legendFormat": "{{db_system}} - {{span_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Db latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Db latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", db_system!=\"\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (db_system, span_name, le))",
       "legendFormat": "{{db_system}} {{span_name}}"
      }
     ]
    },
    {
     "title": "Db error latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", span_kind=\"SPAN_KIND_CLIENT\", db_system!=\"\", status_code=\"STATUS_CODE_ERROR\", cluster=~\"$cluster\", service_version=~\"$version\"}[$__rate_interval])) by (db_system, span_name, le))",
       "legendFormat": "{{db_system}} {{span_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({service_name=\"$service\"}\n    | level=\"info\"\n    | service_version=~\"$version\"\n[$__auto])) by (key_OriginalFormat_)",
       "legendFormat": "{{key_OriginalFormat_}}"
      }
     ]
    },
    {
     "title": "Warning",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({service_name=\"$service\"}\n    | level=\"warning\"\n    | service_version=~\"$version\"\n[$__auto])) by (key_OriginalFormat_)",
       "legendFormat": "{{mt}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({service_name=\"$service\"}\n    | level=\"error\"\n    | service_version=~\"$version\"\n[$__auto])) by (key_OriginalFormat_)",
       "legendFormat": "{{mt}}"
      }
     ]
    },
    {
     "title": "Exception",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({service_name=\"$service\"}\n    | level=\"error\"\n    | service_version=~\"$version\"\n[$__auto])) by (exception_type)",
       "legendFormat": "{{exception_type}}"
      }
     ]
    }
   ]
  }
 ]
}